# Generated by Django 4.2.4 on 2023-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_modified', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='img')),
                ('on_sale', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('toppings', models.ManyToManyField(to='pizzapya.topping')),
            ],
        ),
    ]
