# Generated by Django 4.2.4 on 2023-08-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapya', '0005_alter_topping_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='category',
            field=models.CharField(choices=[('cheeses', 'Cheeses'), ('dessert', 'Dessert'), ('fruits', 'Fruits'), ('gourmet', 'Gourmet'), ('healthy', 'Healthy'), ('herbs_spices', 'Herbs & Spices'), ('meats', 'Meats'), ('nuts_seeds', 'Nuts & Seeds'), ('sauces', 'Sauces'), ('veggies', 'Veggies')], default='Cheeses', max_length=30),
        ),
    ]
