# Generated by Django 4.2.4 on 2023-08-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapya', '0006_alter_topping_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
